### ISSUE TITLE
Clean up XLIFF files for iOS before committing them to Git repository

### ISSUE THREAD

**Issue by flodolo** [translate/mozilla#1]
Per discussion via email: It looks like the main offender (duplicated comments generating files of 10-15 MB each) has been already fixed in the past months, but it would be nice to clean up XLIFF files before committing them to the Git repository.

This is the script used to update locales when new strings are added to en-US
https://github.com/mozilla/firefox-ios-build-tools/blob/master/scripts/update-xliff.py

It basically reads existing translation and inject them in the en-US structure. Using a filter similar to this would reduce the noise, exposing in the history only the strings actually changed. Right now each commit creates a diff that is not visible in GitHub.

Script can be easily changed to only run on a set of locales supported in Pootle, instead of excluding some of them
https://github.com/mozilla/firefox-ios-build-tools/blob/master/scripts/update-xliff.py#L49

**Comment by dwaynebailey** [comment]
@flodolo could you confirm if mozilla-l10n/firefoxios-l10n@0690edb531cf5de797ad51b75c8a9cd6befdf5ba fixes the issue?  For now I've disabled commits until we know it's doing the right thing.

I made some changes to the script to allow locales to be optionally specified, I'll upstream those if we're happy with the results.

**Comment by flodolo** [comment]
The diff looks great (and helped spotted a translation error for a variable).

**Comment by dwaynebailey** [comment]
@flodolo I'll do a batch cleanup to make doubly sure.  Then reenable autocommits.

**Comment by flodolo** [comment]
OK. Let me know when you're done and I can try to run the cleanup script on my side to see the diff.

**Comment by dwaynebailey** [comment]
@flodolo completed all cleanups from my side.

**Comment by dwaynebailey** [comment]
@flodolo I've reenabled autocommit.   And will look to upstream changes to the script.

**Comment by flodolo** [comment]
Confirmed: the diff after running an update is clean for Pootle's locales.
