### ISSUE TITLE
Removing user doesn't work

### ISSUE THREAD

**Issue by unho** [translate/mozilla#3]
Reported by Jeff (and confirmed by me):

the button to delete a user doesn't work, once activated by clicking the box next to it.

**Comment by phlax** [comment]
im wondering if this is the same kind of issue as the adding language - ie it takes a v long time.

I think we should try and doing something similar and make the time consuming parts async - although, im not sure how easy that will be

**Comment by unho** [comment]
Yes, verified and the user is indeed removed, but the removal is not immediately reported.

**Comment by unho** [comment]
Moved to a different tracker, so closing.
