### ISSUE TITLE
Local TM is not enabled

### ISSUE THREAD

**Issue by julen** [translate/mozilla#4]
I'm going through the new Aurora cycle and have 4500+ incomplete words needing attention. While going through them, many strings look very familiar but the lack of local TM forces me to find the results elsewhere and make my time way less productive — when not re-translating. (As a matter of coincidence amagama was down while translating, making the experience even worse).

I don't know if there's a good reason to disable TM but I bet I've been using it on MLO in the past. So please consider this a request to put it back on.

**Comment by unho** [comment]
@julen This should be fixed now. Elasticsearch was down after yesterday's server reboot. Our apologies!
