### ISSUE TITLE
Can't browse iOS project

### ISSUE THREAD

**Issue by julen** [translate/mozilla#6]
Trying to access the iOS project at https://mozilla.locamotion.org/eu/ios/ produces the following error:
```
 Exception: 'NoneType' object has no attribute 'data_tool' 
```

I can also reproduce it with https://mozilla.locamotion.org/ca/ios/. Other locales I tried don't trigger the error. This page was working without problems 2 days ago.

The translation page seems to work ok, and browsing some of the individual files too, except the terminology file. Likewise a file looks to be duplicated in the resources dropdown:
<img width="198" alt="screen shot 2016-11-09 at 18 22 49" src="https://cloud.githubusercontent.com/assets/16768/20147712/88eb5d64-a6a9-11e6-8329-dc94c65c75a3.png">

**Comment by unho** [comment]
This has been fixed. Thanks for reporting and apologies for the inconveniences.
