### ISSUE TITLE
Wrong deadline for Firefox

### ISSUE THREAD

**Issue by julen** [translate/mozilla#8]
The sidebar reads:

>    Translation updates must be completed before Monday, 03 March 2017.

3rd of March is Friday. Nevertheless the date should be Monday, 6th of March, as mentioned by [the report for this cycle](https://blog.mozilla.org/l10n/2017/01/23/firefox-l10n-report-aurora-53/).

**Comment by unho** [comment]
Thanks for reporting. This will be communicated to Mozilla.

**Comment by unho** [comment]
@julen The best way to communicate errors in announcements in the future would be to use the contact form. Thanks again for reporting.
